### ISSUE TITLE
System.ObjectDisposedException: The object has been closed.

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [ratishphilip/CompositionProToolkit#5] opened 2016-08-21 13:22 UTC
Sir it's me again.. this time I got a strange runtime error.. There's a listview in my app's home page.. I loaded 50 items in the listview at a time which looks like this:
![prob 2](https://cloud.githubusercontent.com/assets/9501081/17837382/7eaf4738-67e4-11e6-8fe3-399939ac520d.png)

and as I scroll the listview up and down, my app crashed and throwed this nice little exception: 

```
System.ObjectDisposedException: The object has been closed.

The given object has already been closed / disposed and may no longer be used.
   at Windows.UI.Composition.SpriteVisual.get_Brush()
   at CompositionProToolkit.Controls.CompositionImageFrame.<LoadImageAsync>b__123_1()
   at CompositionExpressionToolkit.CompositorExtensions.<>c__DisplayClass5_0.<CreateScopedBatch>b__0(Object s, CompositionBatchCompletedEventArgs ea)

```

The exception said it tried to dispose an object that is already disposed or to load the object that is has been disposed.. I don't know what object did it refer to.. perhaps you know better since this is your control.
Regards

**Comment by Hanzalah-Adalan** [comment] 2016-08-21 13:25
and it doesn't crash everytime I scroll up and down the listview.. sometimes it crashes sometimes it won't.. that's why I said it was a strange exception..

**Comment by Hanzalah-Adalan** [comment] 2016-08-21 14:06
One thing for sure if I scroll too fast using the listview scrollbar (not using mouse wheel) all the way down to the bottom most of the listview item (which in my case the item at index 49), the app will crash and throw that exception

**Comment by ratishphilip** [comment] 2016-08-21 14:09
@HanAnonymous 
Thanks for reporting this. I have identified the cause of the issue. It will be fixed in the next version.

**Comment by ratishphilip** [comment] 2016-08-25 00:25
@HanAnonymous 
The crash issue is now fixed. Please install the latest NuGet package.

**Closed as completed by ratishphilip** 2016-08-25 00:25 UTC

**Comment by Hanzalah-Adalan** [comment] 2016-08-25 06:03
Thanks for your great effort!

**Comment by naweed** [comment] 2016-09-07 12:07
Hi, Btw, I am on the latest version, and I also notice such issues (app crashing because device is lost or DeviceDispositionException) when I switch between pages multiple times.

**Comment by naweed** [comment] 2016-09-07 12:35
To be specific, this is the error I get. 

The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action. (Exception from HRESULT: 0x887A0005)

Sometimes, I also get something like System.DeviceDispositionException at Microsoft.Graphics.Canvas... (will update when I see it next time).

**Comment by ratishphilip** [comment] 2016-09-07 12:46
@naweed Thanks for the info. 
Which all objects (related to CompositionProToolkit) references are you having in your page? Are you disposing them correctly when the Page is unloaded? If they are not, then it might raise such an issue.

Can you step through your page's code (when you switch pages and return to the page raising the exception) and see which line of code is raising this exception?

**Comment by naweed** [comment] 2016-09-07 12:54
Hi Ratish, I am using ImageFrame inside a gridview on the page.  I have not written any code for page unloaded. Also I noticed that the memory doesn't get released as I keep navigating from page to page, for all the pages where I have used this control.

**Comment by ratishphilip** [comment] 2016-09-07 13:16
ok. I will look into it.

**Comment by naweed** [comment] 2016-09-07 14:23
Thanks. Plz let me know if you need anything from my side.

**Comment by naweed** [comment] 2016-09-08 05:45
@ratishphilip 
Further to issue reported yesterday on memory leak (https://github.com/ratishphilip/CompositionProToolkit/issues/6), if I remove the ImageFrame and replace with regular image (code in the memory leak issue), I don't get the device error at all.

**Comment by Hanzalah-Adalan** [comment] 2016-09-08 12:47
# Lost Devices

When a device is lost, you traditionally need to recreate your graphics device and all of the resources you created with that device. XAML usually handles this for you, but you need to be aware of it when using the Composition APIs.
When can a device be lost? It could be anything from a graphics driver update, to a device that is switching to a different GPU (like with the Surface Book or a laptop disconnecting from something like a Razer Core), or a set of incorrect calls to the GPU that puts it in a bad state and it needs to reset (we call this Timeout Detection and Recovery, otherwise known as TDR). To learn more about lost devices, check out this MSDN article.
While it is not strictly required to handle a lost device, it is greatly recommended that your application is resilient to it. Otherwise when a user detaches their Surface Book from its base with a GPU, your application might lose all of its surfaces! So what do you have to do? If you use CompositionImageLoader you should be set. Just know that if you use LoadImageFromUri or LoadImageFromUriAsync, you’re not protected from a lost graphics device. The ImageLoader does have a DeviceReplacedEvent event you can listen to and redraw your surfaces if you want. However, there’s an even easier way, and that’s by using ManagedSurfaces. If you use CreateManagedSurface or CreateManagedSurfaceAsync and keep the object alive, you won’t have to worry about lost graphics devices (same goes for methods that create a TextSurface). ManagedSurface is the recommended way to go.
One last thing about the ImageLoader, because it creates a graphics device you should try to only keep one around. Creating many of them can become expensive and waste memory. Store it somewhere where you can have good access to it and reuse it. That’s when the ImageLoader can do its best. The ImageLoader makes all of its drawing calls asynchronously (even with the non async methods, the surface creation is synchronous but the ImageLoader draws to it later on) and under a lock, so you shouldn’t have to worry too much about threading. 

copy paste from: http://blog.robmikh.com/uwp/composition/2016/04/21/images-and-effects.html

I don't really understand this thing, but perhaps using IManagedSurface might help

**Comment by ratishphilip** [comment] 2016-09-08 18:15
@Hanzalah-Adalan 
ImageFrame and ImageSurface handle lost devices too in a similar way.
