### ISSUE TITLE
Fluid Wrap Panel: changing the drag "grip" area

### ISSUE THREAD

**Issue by jasonwurzel** [ratishphilip/CompositionProToolkit#12] opened 2017-12-12 11:17 UTC
Hi, 

you have implemented a very nice library here, congratulations! 
One question I have regarding the FluidWrapPanel: In its default implementation, the FluidPointerDragBehavior triggers, no matter where the user clicks on the control. Is there any reasonable possibility, without changing the FluidPointerDragBehavior implementation, to attach the behavior to a child control of the single items, so the drag operation triggers only if the user clicks on this child control, like a grip?
I played a bit with the FluidItemControl in the SampleGallery.sln and changed it as follows, but when dragging I get a System.Collections.Generic.KeyNotFoundException.

```xaml
<Grid>
	<Grid.RowDefinitions>
		<RowDefinition></RowDefinition>
		<RowDefinition Height="Auto"></RowDefinition>
	</Grid.RowDefinitions>
        <Border x:Name="fillBorder"
                Margin="1"
                Background="{Binding Path=Fill, ElementName=parent}"></Border>
        <TextBlock x:Name="numText"
                   FontSize="18"
                   Foreground="White"
                   HorizontalAlignment="Center"
                   VerticalAlignment="Center"
                   Text="{Binding Path=Data, ElementName=parent}"></TextBlock>
		
	<Rectangle Grid.Row="1" Height="30" Fill="Red">
		<Interactivity:Interaction.Behaviors>
			<controls:FluidPointerDragBehavior DragButton="MouseLeftButton"></controls:FluidPointerDragBehavior>
		</Interactivity:Interaction.Behaviors>
	</Rectangle>
</Grid>
```

**Comment by ratishphilip** [comment] 2017-12-19 00:51
Thanks for reporting this issue. Let me check.

**Comment by jasonwurzel** [comment] 2017-12-20 13:37
Hi, 

I created a PR for this (my first one ever, it was about time :-) )

https://github.com/ratishphilip/CompositionProToolkit/pull/13

I didn't take into account/test the ListViewItem case. But I think it should work.

**Comment by ratishphilip** [comment] 2018-01-10 01:28
Hi Jason,

Sorry for the delay in response. I have looked at the issue and found out the cause of this problem.
Though I will be rejecting your pull request, I shall be incorporating the changes you require (in a little different way).

I hope to release the update this week.

Regards,
Ratish

**Comment by ratishphilip** [comment] 2018-01-18 19:06
Hi @jasonwurzel 

This has been fixed in the v0.8 release.
Now it is possible to attach the behavior to a child control of the single items, so the drag operation triggers only if the user clicks on this child control, like a grip.

**Closed as completed by ratishphilip** 2018-01-18 19:06 UTC
Labels: bug

**Comment by jasonwurzel** [comment] 2018-01-19 05:23
Hey @ratishphilip , 

thanks for the reply. I haven't had time to look into it but I'm curious as to how you implemented/fixed it.

**Comment by ratishphilip** [comment] 2018-01-19 05:29
@jasonwurzel I had to rewrite the FluidPointerDragBehavior class and some minor modification in the FluidWrapPanel.
The element to which the behavior is attached will raise the Pointer events, but the position is calculated w.r.t. the ancestor of the element which is also the child of the FluidWrapPanel.
